apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  clusterIP: None
  ports:
  - name: etcd-client
    port: 2379
  - name: etcd-server
    port: 2380
  selector:
    app: etcd
