# permissions for end users to edit kubeapiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubeapiserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeception-operator
    app.kubernetes.io/part-of: kubeception-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeapiserver-editor-role
rules:
- apiGroups:
  - cluster.kubeception.ulfo.fr
  resources:
  - kubeapiservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kubeception.ulfo.fr
  resources:
  - kubeapiservers/status
  verbs:
  - get
